name: Auto Reply on Issue Creation
on:
  issues:
    types:
      - opened

jobs:
  auto-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm install -g github-actions-reply-comment

      - name: Reply as Repository Owner
        run: |
          GITHUB_TOKEN=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 github-actions-reply-comment --issue-number ${{ github.event.issue.number }} --body "Thank you for creating the issue. We will look into it shortly."

