name: Auto Reply on Issue Creation
on:
  issues:
    types:
      - opened

jobs:
  auto-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Reply as Repository Owner
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const response = await github.issues.createComment({
              owner,
              repo,
              issue_number: issueNumber,
              body: "Thank you for creating the issue. We will look into it shortly."
            });

            console.log("Reply created:", response);
