name: Comment and Label on Issue Opened
on:
  issues:
    types:
      - opened

jobs:
  comment_and_label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const commentAuthor = context.payload.issue.user.login;
            const commentBody = `Hey @${commentAuthor} ! \n  Thank you for creating issue in shorttime maintainer of repo review your issue thank you 👾   `;
            const { owner, repo, number } = context.issue;

            await github.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: number,
              body: commentBody
            });

      - name: Add label if issue body contains "GSSoC23"
        id: check_label
        run: |
          if [[ $(echo "${{ github.event.issue.body }}" | grep -q "GSSoC23"; echo $?) == 0 ]]; then
            echo "::set-output name=add_label::true"
          else
            echo "::set-output name=add_label::false"
          fi

      - name: Add label "GSSoC23"
        if: ${{ steps.check_label.outputs.add_label == 'true' }}
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;

            await github.issues.addLabels({
              owner: owner,
              repo: repo,
              issue_number: number,
              labels: ["gssoc23"]
            });
